version: '3.5'

services:
  app:
    build: .docker/c
    working_dir: /app
    volumes:
      - .:/app
    environment:
      SOURCE_DIRECTORY: ./src
      TEST_DIRECTORIES: ./src/Tests
      TEST_SUFFIXES: Test.c
    # entrypoint: 'tail -f /dev/null'
